import os
import json
from openai import OpenAI

client = OpenAI(
    api_key=os.getenv("TYPHOON_API_KEY"),
    base_url="https://api.opentyphoon.ai/v1",
)

def analyze_requirement(raw_text: str) -> list[dict]:
    """
    Accept requirement text and return a list of tasks generated by the AI.
    Each task includes: title, description, estimated_hours, and priority.
    """
    prompt = f"""คุณคือ AI Project Manager อ่าน requirement ต่อไปนี้แล้วแตกเป็น task ย่อย ๆ

Requirement:
{raw_text}

ตอบกลับเป็น JSON array เท่านั้น ห้ามมีข้อความอื่นนอกเหนือจาก JSON ในรูปแบบนี้:
[
  {{"title": "ชื่อ task", "description": "รายละเอียด", "estimated_hours": 4, "priority": "medium"}}
]
priority ต้องเป็นหนึ่งใน: low, medium, high
"""

    response = client.chat.completions.create(
    model="typhoon-v2.5-30b-a3b-instruct",
    messages=[{"role": "user", "content": prompt}],
    temperature=0.3,
    max_tokens=2048,
    )

    content = response.choices[0].message.content.strip()

    if content.startswith("```"):
        content = content.strip("`")
        content = content.replace("json", "", 1).strip()

    try:
        tasks = json.loads(content)
        return tasks
    except json.JSONDecodeError:
        raise ValueError(f"The AI response is not valid JSON.: {content}")
    
def recommend_assignee(task_title: str, task_description: str, candidates: list[dict]) -> dict:
    """
    candidates: a list of dicts, e.g.
    [{"user_id": 2, "name": "mameaw", "skills": ["React", "Python"], "current_task_count": 3}]
    Return: {"user_id": 2, "reason": "Reason for selecting this user"}
    """
    candidates_text = "\n".join(
        f"- user_id: {c['user_id']}, Name: {c['name']}, skills: {', '.join(c['skills']) or 'No data'}, Current tasks.: {c['current_task_count']} task"
        for c in candidates
    )

    prompt = f"""คุณคือ AI Project Manager ต้องเลือกคนที่เหมาะสมที่สุดสำหรับ task นี้

Task: {task_title}
รายละเอียด: {task_description}

รายชื่อผู้สมัครที่เลือกได้:
{candidates_text}

พิจารณาจากทักษะที่ตรงกับ task และภาระงานปัจจุบัน (คนที่งานน้อยกว่าควรได้รับความสำคัญถ้าทักษะพอ ๆ กัน)

ตอบกลับเป็น JSON เท่านั้น ห้ามมีข้อความอื่น รูปแบบนี้:
{{"user_id": <id ที่เลือก>, "reason": "เหตุผลสั้น ๆ ที่เลือกคนนี้"}}
"""

    response = client.chat.completions.create(
        model="typhoon-v2.5-30b-a3b-instruct",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.3,
        max_tokens=512,
    )

    content = response.choices[0].message.content.strip()
    if content.startswith("```"):
        content = content.strip("`")
        content = content.replace("json", "", 1).strip()

    try:
        result = json.loads(content)
        return result
    except json.JSONDecodeError:
        raise ValueError(f"The AI response is not valid JSON: {content}")
    
    
def classify_intent(text: str) -> str:
    """
    Classify the message as either 'question' (a serious question) or 'greeting' (greeting, thanking, or casual conversation).
    Return: "question" or "greeting"
    """
    prompt = f"""แยกประเภทข้อความต่อไปนี้ว่าเป็นประเภทไหน

ข้อความ: "{text}"

ประเภทที่เป็นไปได้:
- "question" คือคำถามที่ต้องการข้อมูล/คำตอบจริงจัง เช่น ถามเกี่ยวกับ requirement, task, ระบบ
- "greeting" คือคำทักทาย คำขอบคุณ คำลา หรือคำพูดทั่วไปที่ไม่ต้องการข้อมูลเฉพาะเจาะจง เช่น "สวัสดี", "ขอบคุณครับ", "โอเค"

ตอบกลับเป็นคำเดียวเท่านั้น: question หรือ greeting ห้ามมีคำอธิบายเพิ่ม"""

    response = client.chat.completions.create(
        model="typhoon-v2.5-30b-a3b-instruct",
        messages=[{"role": "user", "content": prompt}],
        temperature=0,
        max_tokens=10,
    )

    result = response.choices[0].message.content.strip().lower()

    if "greeting" in result:
        return "greeting"
    return "question"